<?php
/**
 * WordPress configuration file generated by ddev-orchestrate.
 */

define( 'DB_NAME', '{{DB_NAME}}' );
define( 'DB_USER', '{{DB_USER}}' );
define( 'DB_PASSWORD', '{{DB_PASSWORD}}' );
define( 'DB_HOST', '{{DB_HOST}}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**
 * Authentication unique keys and salts.
 *
 * In DDEV these don't need to be secret.
 */
define( 'AUTH_KEY',         'ddev-orchestrate' );
define( 'SECURE_AUTH_KEY',  'ddev-orchestrate' );
define( 'LOGGED_IN_KEY',    'ddev-orchestrate' );
define( 'NONCE_KEY',        'ddev-orchestrate' );
define( 'AUTH_SALT',        'ddev-orchestrate' );
define( 'SECURE_AUTH_SALT', 'ddev-orchestrate' );
define( 'LOGGED_IN_SALT',   'ddev-orchestrate' );
define( 'NONCE_SALT',       'ddev-orchestrate' );

$table_prefix = 'wp_';

define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'SCRIPT_DEBUG', true );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
