name: sovereignty
type: php
docroot: .ddev/wordpress
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
database:
    type: mariadb
    version: "10.11"
composer_version: "2"
nodejs_version: "22"
